/* Automatically generated by ast-gen. DO NOT MODIFY. */
#pragma once
#include "Node.hpp"
#include <vector>
#include <string>
#include <boost/smart_ptr.hpp>
#include <stdexcept>

namespace ast {

using std::vector;
using std::string;
using boost::shared_ptr;
using std::runtime_error;

class FuncArg : public Node
{
public:
	FuncArg() : Node() {}

	virtual bool isKindOf(Kind k)
	{
		if (Node::isKindOf(k)) return true;
		return k == kFuncArg;
	}

	void setName(const string& v)
	{
		if (v != name) {
			modify();
			name = v;
		}
	}
	const string& getName()
	{
		return name;
	}

	void setType(const string& v)
	{
		if (v != type) {
			modify();
			type = v;
		}
	}
	const string& getType()
	{
		return type;
	}

protected:
	string name;
	string type;
};

} // namespace ast