language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-dev libboost-test-dev libboost-system-dev libboost-filesystem-dev
script:
  - mkdir build
  - cd build
  - export CTEST_OUTPUT_ON_FAILURE=1
  - cmake .. && make && ctest
