language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-dev libboost-test-dev libboost-system-dev libboost-filesystem-dev
  - sudo pip install cpp-coveralls
script:
  - export CTEST_OUTPUT_ON_FAILURE=1
  - cmake -DENABLE_GCOV=ON . && make && make test
after_success:
  - coveralls -E "maxwell/(gen|test)" -E "maxwell/driver/(Parser|Scanner).cpp" -e CMakeFiles --gcov-options '\-lp'
