/* Copyright © 2013 Fabian Schuiki */
#pragma once

#ifndef YY_DECL
#define YY_DECL example::Parser::token_type example::Scanner::lex(\
	example::Parser::semantic_type* yylval,\
	example::Parser::location_type* yylloc\
)
#endif

#ifndef __FLEX_LEXER_H
#define yyFlexLexer ExampleFlexLexer
#include "FlexLexer.h"
#undef yyFlexLexer
#endif

#include "Parser.hpp"

namespace example {

/**
 * Scanner is a convenience wrapper class around the Flex-generated
 * ExampleFlexLexer class. It adds some extra functionality to the scanner.
 */
class Scanner : public ExampleFlexLexer
{
public:
	Scanner(std::istream* in = 0, std::ostream* out = 0);
	virtual ~Scanner();

	/**
	 * This is the main lexing function generated by Flex according to the
	 * definition of YY_DECL above.
	 */
	virtual Parser::token_type lex(Parser::semantic_type* yylval, Parser::location_type* yylloc);
};

} // namespace example