/* Copyright (c) 2013 Fabian Schuiki */
#pragma once

#ifndef YY_DECL
#define YY_DECL driver::Parser::token_type driver::Scanner::lex(\
	driver::Parser::semantic_type* yylval,\
	driver::Parser::location_type* yylloc\
)
#endif

#ifndef __FLEX_LEXER_H
#define yyFlexLexer DriverFlexLexer
#include "FlexLexer.h"
#undef yyFlexLexer
#endif

#include "Parser.hpp"

namespace driver {

/**
 * Scanner is a convenience wrapper class around the Flex-generated
 * DriverFlexLexer class. It adds some extra functionality to the scanner.
 */
class Scanner : public DriverFlexLexer {
public:
	Scanner(std::istream* in = 0, std::ostream* out = 0);
	virtual ~Scanner();

	/**
	 * This is the main lexing function generated by Flex according to the
	 * definition of YY_DECL above.
	 */
	virtual Parser::token_type lex(
		Parser::semantic_type* yylval,
		Parser::location_type* yylloc
	);
};

} // namespace driver
