<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gcov</string>
	</array>
	<key>name</key>
	<string>gcov</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^\s*-\s*:</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.gcov</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*#+\s*:</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>invalid.untouched.gcov</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.gcov</string>
	<key>uuid</key>
	<string>228333b2-d640-4319-8fc5-4693fd593bac</string>
</dict>
</plist>
