/* Copyright (c) 2013 Fabian Schuiki */

struct ConstArray_Int3 {
	int length;
	int elements[3];
};
struct ConstArray_Int4 {
	int length;
	int elements[4];
};

void main()
{
	int a = 0;

	/* These statements are generated by the constant array literals within the
	 * for loop. */
	struct ConstArray_Int3 tmp0 = {3, {0, 1, 2}};
	struct ConstArray_Int4 tmp1 = {4, {0, 1, 2, 3}};

	/* Each "in" expression within the iteration body of the for loop is
	 * converted into its own for loop. Note that the iteration variables i and
	 * j are copies of the loop variables. This is due to the fact that the
	 * loop body and iteration body may apply changes to these variables. */
	int tmp2;
	for (tmp2 = 0; tmp2 < tmp0.length; tmp2++) {
		int i = tmp2;
		if (i == 1) continue;
		int tmp3;
		for (tmp3 = 0; tmp3 < tmp1.length; tmp3++) {
			int j = tmp3;
			if (j == 2) continue;

			/* The loop body starts here. */
			a += i * j;
		}
	}
}
