/* Automatically generated by ast-gen. DO NOT MODIFY. */
#pragma once
#include "../Node.hpp"
#include "../Coder.hpp"
#include <vector>
#include <string>
#include <sstream>
#include <boost/smart_ptr.hpp>
#include <stdexcept>

namespace ast {

using std::vector;
using std::string;
using std::stringstream;
using std::endl;
using std::runtime_error;

class FuncBody : public Node
{
public:
	FuncBody() : Node() {}

	virtual bool isKindOf(Kind k)
	{
		if (Node::isKindOf(k)) return true;
		return k == kFuncBody;
	}

	virtual string getClassName() const { return "FuncBody"; }

	void setStmts(const NodeVector& v)
	{
		if (v != stmts) {
			modify();
			stmts = v;
		}
	}
	const NodeVector& getStmts()
	{
		return stmts;
	}

	virtual string describe(int depth = -1)
	{
		if (depth == 0) return "FuncBody{…}";
		stringstream str, b;
		str << "FuncBody{";
		if (!this->stmts.empty()) b << endl << "  \033[1mstmts\033[0m = " << indent(describeVector(this->stmts, depth-1)) << "";
		string bs = b.str();
		if (!bs.empty()) str << bs << endl;
		str << "}";
		return str.str();
	}

	virtual void encode(Encoder& e)
	{
		e.encode(this->stmts);
	}

	virtual void decode(Decoder& d)
	{
		d.decode(this->stmts);
	}

protected:
	NodeVector stmts;
};

} // namespace ast