/* Automatically generated by ast-gen. DO NOT MODIFY. */
#pragma once

namespace ast {

/// Node kinds that may be used to test whether a Node is of a given subclass.
typedef enum {
	kArrayConstExpr,
	kAssignmentExpr,
	kBinaryOpExpr,
	kCallArg,
	kCallCandidate,
	kCallCandidateArg,
	kCallExpr,
	kCallExprArg,
	kDefinedType,
	kExprStmt,
	kFuncArg,
	kFuncBody,
	kFuncDef,
	kFuncType,
	kGenericType,
	kIdentifierExpr,
	kImplAccessor,
	kImplAccessorArg,
	kInterfaceQualifier,
	kInvalidType,
	kMapConstExpr,
	kMapConstExprPair,
	kMemberAccessExpr,
	kNamedTypeExpr,
	kNativeQualifier,
	kNumberConstExpr,
	kQualifiedType,
	kQualifiedTypeExpr,
	kQualifiedTypeMember,
	kRangeQualifier,
	kSetConstExpr,
	kStringConstExpr,
	kStructureQualifier,
	kStructureQualifierMember,
	kTupleType,
	kTupleTypeArg,
	kTupleTypeExpr,
	kTupleTypeExprArg,
	kTypeDef,
	kTypeSet,
	kUnaryOpExpr,
	kUnionType,
	kUnionTypeExpr,
	kVarDefExpr
} Kind;

/// Node interfaces that may be used to test whether a Node implements a given interface.
typedef enum {
	kCallInterface,
	kCallArgInterface,
	kCallableInterface,
	kCallableArgInterface,
	kGraphInterface,
	kNamedInterface,
	kTypeInterface,
	kTypeExprInterface,
	kVariableInterface
} Interface;

} // namespace ast

