/* Automatically generated by ast-gen. DO NOT MODIFY. */
#pragma once
#include "../Node.hpp"
#include "../Coder.hpp"
#include "interfaces.hpp"
#include <vector>
#include <string>
#include <sstream>
#include <boost/smart_ptr.hpp>
#include <stdexcept>
#include <cstdio>

namespace ast {

using std::vector;
using std::string;
using std::stringstream;
using std::endl;
using std::runtime_error;

class DefinedType : public Node
{
public:
	DefinedType() : Node() {}

	virtual bool isKindOf(Kind k)
	{
		if (Node::isKindOf(k)) return true;
		return k == kDefinedType;
	}

	virtual bool implements(Interface i)
	{
		if (Node::implements(i)) return true;
		return false;
	}

	virtual string getClassName() const { return "DefinedType"; }

	virtual NodePtr copy()
	{
		Ptr c (new DefinedType);
		Node::copy(this->definition, c->definition);
		return c;
	}

	void setDefinition(const NodePtr& v)
	{
		if (!v && definition) {
			modify("definition");
			definition.reset();
		}
		if (!definition || v->getId() != definition.id) {
			modify("definition");
			definition.set(v);
		}
	}
	void setDefinition(const NodeId& v)
	{
		if (v != definition.id) {
			modify("definition");
			definition.set(v);
		}
	}
	const NodePtr& getDefinition(bool required = true)
	{
		const NodePtr& v = definition.get(repository);
		if (required && !v) {
			throw runtime_error("Node " + getId().str() + " is required to have definition set to a non-null value.");
		}
		return v;
	}

	virtual string describe(int depth = -1)
	{
		stringstream str, b;
		str << (getDefinition()->implements(kNamedInterface) ? getDefinition()->needNamed()->getName() : getDefinition()->getId().str());
		return str.str();
	}

	virtual void encode(Encoder& e)
	{
		e.encode(this->definition);
	}

	virtual void decode(Decoder& d)
	{
		d.decode(this->definition);
	}

	virtual void updateHierarchyOfChildren()
	{
	}

	virtual const NodePtr& resolvePath(const string& path)
	{
		size_t size = path.size();
		// definition.*
		if (size >= 10 && path[0] == 'd' && path[1] == 'e' && path[2] == 'f' && path[3] == 'i' && path[4] == 'n' && path[5] == 'i' && path[6] == 't' && path[7] == 'i' && path[8] == 'o' && path[9] == 'n') {
			// definition
			if (size == 10) {
				return getDefinition();
			} else if (path[10] == '.') {
				return getDefinition()->resolvePath(path.substr(11));
			}
		}
		throw std::runtime_error("Node path '" + path + "' does not point to a node or array of nodes.");
	}

	virtual bool equalTo(const NodePtr& o)
	{
		const shared_ptr<DefinedType>& other = boost::dynamic_pointer_cast<DefinedType>(o);
		if (!other) return false;
		if (!equal(this->definition, other->definition)) return false;
		return true;
	}

	typedef boost::shared_ptr<DefinedType> Ptr;
	template<typename T> static Ptr from(const T& n) { return boost::dynamic_pointer_cast<DefinedType>(n); }
	template<typename T> static Ptr needFrom(const T& n) { Ptr r = boost::dynamic_pointer_cast<DefinedType>(n); if (!r) throw std::runtime_error("Node " + n->getId().str() + " cannot be dynamically casted to DefinedType."); return r; }
protected:
	NodeRef definition;
};

} // namespace ast