/* Automatically generated by ast-gen. DO NOT MODIFY. */
#pragma once
#include "../Node.hpp"
#include "interfaces.hpp"
#include "types.hpp"

namespace ast {

class Encoder;
class Decoder;

class MapConstExprPair : public Node
{
public:
	// constructor
	MapConstExprPair();

	// auxiliary functions
	virtual bool isKindOf(Kind k);
	virtual bool implements(Interface i);
	virtual std::string getClassName() const { return "MapConstExprPair"; }
	virtual NodePtr copy();
	virtual bool equalTo(const NodePtr& o);
	virtual std::string describe(int depth = -1);

	// accessor functions
	void setGraphPrev(const NodePtr& v);
	void setGraphPrev(const NodeId& v);
	const NodePtr& getGraphPrev(bool required = true);

	void setKey(const NodePtr& v);
	const NodePtr& getKey(bool required = true);

	void setValue(const NodePtr& v);
	const NodePtr& getValue(bool required = true);

	// encoding and decoding
	virtual void encode(Encoder& e);
	virtual void decode(Decoder& d);

	// hierarchy functions
	virtual void updateHierarchyOfChildren();
	virtual const NodePtr& resolvePath(const std::string& path);
	virtual NodeVector getChildren();

	// interfaces
	virtual GraphInterface* asGraph() { return &this->interfaceGraph; }

	// shared_ptr convenience
	typedef boost::shared_ptr<MapConstExprPair> Ptr;
	template<typename T> static Ptr from(const T& n) { return boost::dynamic_pointer_cast<MapConstExprPair>(n); }
	template<typename T> static Ptr needFrom(const T& n) {
		Ptr r = boost::dynamic_pointer_cast<MapConstExprPair>(n);
		if (!r)
			throw std::runtime_error("Node " + n->getId().str() + " (a " + n->getClassName() + ") cannot be dynamically cast to MapConstExprPair.");
		return r;
	}

protected:
	NodeRef graphPrev;
	NodePtr key;
	NodePtr value;

	// interfaces
	GraphInterfaceImpl<MapConstExprPair> interfaceGraph;
};

} // namespace ast
