/* Automatically generated by ast-gen. DO NOT MODIFY. */
#pragma once
#include "maxwell/ast/Node.hpp"
#include "maxwell/ast/nodes/interfaces.hpp"
#include "maxwell/ast/nodes/types.hpp"

namespace ast {

class Encoder;
class Decoder;

class IfCaseExprCond : public Node
{
public:
	// constructor
	IfCaseExprCond();

	// auxiliary functions
	virtual bool isKindOf(Kind k);
	virtual bool implements(Interface i);
	virtual std::string getClassName() const { return "IfCaseExprCond"; }
	virtual NodePtr copy();
	virtual bool equalTo(const NodePtr& o);
	virtual std::string describe(int depth = -1);

	// accessor functions
	void setExpr(const NodePtr& v);
	const NodePtr& getExpr(bool required = true);

	void setCond(const NodePtr& v);
	const NodePtr& getCond(bool required = true);

	void setGraphPrev(const NodePtr& v);
	void setGraphPrev(const NodeId& v);
	const NodePtr& getGraphPrev(bool required = true);

	// encoding and decoding
	virtual void encode(Encoder& e);
	virtual void decode(Decoder& d);

	// hierarchy functions
	virtual void updateHierarchyOfChildren();
	virtual const NodePtr& resolvePath(const std::string& path);
	virtual NodeVector getChildren();

	// interfaces
	virtual GraphInterface* asGraph() { return &this->interfaceGraph; }

	// shared_ptr convenience
	typedef boost::shared_ptr<IfCaseExprCond> Ptr;
	template<typename T> static Ptr from(const T& n) { return boost::dynamic_pointer_cast<IfCaseExprCond>(n); }
	template<typename T> static Ptr needFrom(const T& n) {
		Ptr r = boost::dynamic_pointer_cast<IfCaseExprCond>(n);
		if (!r)
			throw std::runtime_error("Node " + n->getId().str() + " (a " + n->getClassName() + ") cannot be dynamically cast to IfCaseExprCond.");
		return r;
	}

protected:
	NodePtr expr;
	NodePtr cond;
	NodeRef graphPrev;

	// interfaces
	GraphInterfaceImpl<IfCaseExprCond> interfaceGraph;
};

} // namespace ast
