/* Automatically generated by ast-gen. DO NOT MODIFY. */
#pragma once
#include "maxwell/ast/Node.hpp"
#include "maxwell/ast/nodes/interfaces.hpp"
#include "maxwell/ast/nodes/types.hpp"

namespace ast {

class Encoder;
class Decoder;

class NativeFuncDef : public Node
{
public:
	// constructor
	NativeFuncDef();

	// auxiliary functions
	virtual bool isKindOf(Kind k);
	virtual bool implements(Interface i);
	virtual std::string getClassName() const { return "NativeFuncDef"; }
	virtual NodePtr copy();
	virtual bool equalTo(const NodePtr& o);
	virtual std::string describe(int depth = -1);

	// accessor functions
	void setGraphPrev(const NodePtr& v);
	void setGraphPrev(const NodeId& v);
	const NodePtr& getGraphPrev(bool required = true);

	void setName(const std::string& v);
	const std::string& getName(bool required = true);

	void setIn(const NodeVector& v);
	const NodeVector& getIn(bool required = true);

	void setOut(const NodeVector& v);
	const NodeVector& getOut(bool required = true);

	void setType(const NodePtr& v);
	const NodePtr& getType(bool required = true);

	// encoding and decoding
	virtual void encode(Encoder& e);
	virtual void decode(Decoder& d);

	// hierarchy functions
	virtual void updateHierarchyOfChildren();
	virtual const NodePtr& resolvePath(const std::string& path);
	virtual NodeVector getChildren();

	// interfaces
	virtual CallableInterface* asCallable() { return &this->interfaceCallable; }
	virtual GraphInterface* asGraph() { return &this->interfaceGraph; }
	virtual NamedInterface* asNamed() { return &this->interfaceNamed; }

	// shared_ptr convenience
	typedef boost::shared_ptr<NativeFuncDef> Ptr;
	template<typename T> static Ptr from(const T& n) { return boost::dynamic_pointer_cast<NativeFuncDef>(n); }
	template<typename T> static Ptr needFrom(const T& n) {
		Ptr r = boost::dynamic_pointer_cast<NativeFuncDef>(n);
		if (!r)
			throw std::runtime_error("Node " + n->getId().str() + " (a " + n->getClassName() + ") cannot be dynamically cast to NativeFuncDef.");
		return r;
	}

protected:
	NodeRef graphPrev;
	std::string name;
	NodeVector in;
	NodeVector out;
	NodePtr type;

	// interfaces
	CallableInterfaceImpl<NativeFuncDef> interfaceCallable;
	GraphInterfaceImpl<NativeFuncDef> interfaceGraph;
	NamedInterfaceImpl<NativeFuncDef> interfaceNamed;
};

} // namespace ast
