/* Automatically generated by ast-gen. DO NOT MODIFY. */
#include "maxwell/ast/nodes/NativeFuncDef.hpp"
#include "maxwell/ast/Coder.hpp"
#include <cstdio>
#include <sstream>
#include <stdexcept>
using ast::NativeFuncDef;
using ast::NodePtr;
using ast::NodeVector;

NativeFuncDef::NativeFuncDef() : Node(),
	interfaceCallable(this),
	interfaceGraph(this),
	interfaceNamed(this) {}

bool NativeFuncDef::isKindOf(Kind k) {
	if (Node::isKindOf(k)) return true;
	return k == kNativeFuncDef;
}

bool NativeFuncDef::implements(Interface i) {
	if (Node::implements(i)) return true;
	if (i == kCallableInterface) return true;
	if (i == kGraphInterface) return true;
	if (i == kNamedInterface) return true;
	return false;
}

NodePtr NativeFuncDef::copy() {
	Ptr c (new NativeFuncDef);
	Node::copy(this->graphPrev, c->graphPrev);
	Node::copy(this->name, c->name);
	Node::copy(this->in, c->in);
	Node::copy(this->out, c->out);
	Node::copy(this->type, c->type);
	return c;
}

bool NativeFuncDef::equalTo(const NodePtr& o) {
	const shared_ptr<NativeFuncDef>& other = boost::dynamic_pointer_cast<NativeFuncDef>(o);
	if (!other) return false;
	if (!equal(this->graphPrev, other->graphPrev)) return false;
	if (!equal(this->name, other->name)) return false;
	if (!equal(this->in, other->in)) return false;
	if (!equal(this->out, other->out)) return false;
	if (!equal(this->type, other->type)) return false;
	return true;
}

std::string NativeFuncDef::describe(int depth) {
	std::stringstream str, b;
	if (depth == 0) return "NativeFuncDef{…}";
	str << "NativeFuncDef{";
	if (this->graphPrev) b << "\n  \033[1mgraphPrev\033[0m = \033[36m" << this->graphPrev.id << "\033[0m";
	if (!this->name.empty()) b << "\n  \033[1mname\033[0m = \033[33m\"" << this->name << "\"\033[0m";
	if (!this->in.empty()) b << "\n  \033[1min\033[0m = " << indent(describeVector(this->in, depth-1));
	if (!this->out.empty()) b << "\n  \033[1mout\033[0m = " << indent(describeVector(this->out, depth-1));
	if (this->type) b << "\n  \033[1mtype\033[0m = " << indent(this->type->describe(depth-1));
	string bs = b.str();
	if (!bs.empty()) str << bs << '\n';
	str << "}";
	return str.str();
}


void NativeFuncDef::setGraphPrev(const NodePtr& v) {
	if (!v && graphPrev) {
		modify("graphPrev");
		graphPrev.reset();
	}
	if (!graphPrev || v->getId() != graphPrev.id) {
		modify("graphPrev");
		graphPrev.set(v);
	}
}

void NativeFuncDef::setGraphPrev(const NodeId& v) {
	if (v != graphPrev.id) {
		modify("graphPrev");
		graphPrev.set(v);
	}
}

const NodePtr& NativeFuncDef::getGraphPrev(bool required) {
	const NodePtr& v = graphPrev.get(repository);
	if (required && !v) {
		throw std::runtime_error("Node " + getId().str() + " is required to have graphPrev set to a non-null value.");
	}
	return v;
}


void NativeFuncDef::setName(const std::string& v) {
	if (!equal(v, name)) {
		modify("name");
		name = v;
	}
}

const std::string& NativeFuncDef::getName(bool required) {
	const std::string& v = name;
	if (required && v.empty()) {
		throw std::runtime_error("Node " + getId().str() + " is required to have a non-empty string name set.");
	}
	return v;
}


void NativeFuncDef::setIn(const NodeVector& v) {
	if (!equal(v, in)) {
		modify("in");
		in = v;
	}
}

const NodeVector& NativeFuncDef::getIn(bool required) {
	const NodeVector& v = in;
	return v;
}


void NativeFuncDef::setOut(const NodeVector& v) {
	if (!equal(v, out)) {
		modify("out");
		out = v;
	}
}

const NodeVector& NativeFuncDef::getOut(bool required) {
	const NodeVector& v = out;
	return v;
}


void NativeFuncDef::setType(const NodePtr& v) {
	if (v && !v->isKindOf(kFuncType)) {
		throw std::runtime_error("'type' of " + id.str() + " needs to be of kind {FuncType} or implement interface {}, got " + v->getClassName() + " (" + v->getId().str() + ") instead.");
	}
	if (!equal(v, type)) {
		modify("type");
		type = v;
	}
}

const NodePtr& NativeFuncDef::getType(bool required) {
	const NodePtr& v = type;
	if (required && !v) {
		throw std::runtime_error("Node " + getId().str() + " is required to have type set to a non-null value.");
	}
	return v;
}


void NativeFuncDef::encode(Encoder& e) {
	e.encode(this->graphPrev);
	e.encode(this->name);
	e.encode(this->in);
	e.encode(this->out);
	e.encode(this->type);
}

void NativeFuncDef::decode(Decoder& d) {
	d.decode(this->graphPrev);
	d.decode(this->name);
	d.decode(this->in);
	d.decode(this->out);
	d.decode(this->type);
}


void NativeFuncDef::updateHierarchyOfChildren() {
	for (unsigned i = 0; i < this->in.size(); i++) {
		char buf[32]; snprintf(buf, 31, "%i", i);
		this->in[i]->updateHierarchy((id + "in") + buf, repository, this);
	}
	for (unsigned i = 0; i < this->out.size(); i++) {
		char buf[32]; snprintf(buf, 31, "%i", i);
		this->out[i]->updateHierarchy((id + "out") + buf, repository, this);
	}
	if (this->type) this->type->updateHierarchy(id + "type", repository, this);
}

const NodePtr& NativeFuncDef::resolvePath(const std::string& path) {
	size_t size = path.size();
	// .*
	if (true) {
		// graphPrev.*
		if (size >= 9 && path[0] == 'g' && path[1] == 'r' && path[2] == 'a' && path[3] == 'p' && path[4] == 'h' && path[5] == 'P' && path[6] == 'r' && path[7] == 'e' && path[8] == 'v') {
			// graphPrev
			if (size == 9) {
				return getGraphPrev();
			} else if (path[9] == '.') {
				return getGraphPrev()->resolvePath(path.substr(10));
			}
		}
		// in.*
		if (size >= 2 && path[0] == 'i' && path[1] == 'n') {
			// in
			if (size == 2) {
				throw std::runtime_error("Path '" + path + "' refers to an array instead of a concrete array element.");
			} else if (path[2] == '.') {
				size_t dot = path.find(".", 3);
				string idx_str = path.substr(3, dot);
				int idx = atoi(idx_str.c_str());
				const NodeVector& a = getIn();
				if (idx < 0 || idx >= (int)a.size()) {
					throw std::runtime_error("Index into array '" + path.substr(0, 2) + "' is out of bounds.");
				}
				if (dot == string::npos) {
					return a[idx];
				} else {
					return a[idx]->resolvePath(path.substr(dot + 1));
				}
			}
		}
		// out.*
		if (size >= 3 && path[0] == 'o' && path[1] == 'u' && path[2] == 't') {
			// out
			if (size == 3) {
				throw std::runtime_error("Path '" + path + "' refers to an array instead of a concrete array element.");
			} else if (path[3] == '.') {
				size_t dot = path.find(".", 4);
				string idx_str = path.substr(4, dot);
				int idx = atoi(idx_str.c_str());
				const NodeVector& a = getOut();
				if (idx < 0 || idx >= (int)a.size()) {
					throw std::runtime_error("Index into array '" + path.substr(0, 3) + "' is out of bounds.");
				}
				if (dot == string::npos) {
					return a[idx];
				} else {
					return a[idx]->resolvePath(path.substr(dot + 1));
				}
			}
		}
		// type.*
		if (size >= 4 && path[0] == 't' && path[1] == 'y' && path[2] == 'p' && path[3] == 'e') {
			// type
			if (size == 4) {
				return getType();
			} else if (path[4] == '.') {
				return getType()->resolvePath(path.substr(5));
			}
		}
	}
	throw std::runtime_error("Node path '" + path + "' does not point to a node or array of nodes.");
}

NodeVector NativeFuncDef::getChildren() {
	NodeVector v;
	v.insert(v.end(), this->in.begin(), this->in.end());
	v.insert(v.end(), this->out.begin(), this->out.end());
	if (const NodePtr& n = this->getType(false)) v.push_back(n);
	return v;
}

