/* Automatically generated by ast-gen. DO NOT MODIFY. */
#include "maxwell/ast/nodes/RangeQualifier.hpp"
#include "maxwell/ast/Coder.hpp"
#include <cstdio>
#include <sstream>
#include <stdexcept>
using ast::RangeQualifier;
using ast::NodePtr;
using ast::NodeVector;

RangeQualifier::RangeQualifier() : Node(),
	interfaceGraph(this),
	interfaceNamed(this) {}

bool RangeQualifier::isKindOf(Kind k) {
	if (Node::isKindOf(k)) return true;
	return k == kRangeQualifier;
}

bool RangeQualifier::implements(Interface i) {
	if (Node::implements(i)) return true;
	if (i == kGraphInterface) return true;
	if (i == kNamedInterface) return true;
	return false;
}

NodePtr RangeQualifier::copy() {
	Ptr c (new RangeQualifier);
	Node::copy(this->graphPrev, c->graphPrev);
	Node::copy(this->name, c->name);
	Node::copy(this->min, c->min);
	Node::copy(this->max, c->max);
	return c;
}

bool RangeQualifier::equalTo(const NodePtr& o) {
	const shared_ptr<RangeQualifier>& other = boost::dynamic_pointer_cast<RangeQualifier>(o);
	if (!other) return false;
	if (!equal(this->graphPrev, other->graphPrev)) return false;
	if (!equal(this->name, other->name)) return false;
	if (!equal(this->min, other->min)) return false;
	if (!equal(this->max, other->max)) return false;
	return true;
}

std::string RangeQualifier::describe(int depth) {
	std::stringstream str, b;
	if (depth == 0) return "RangeQualifier{…}";
	str << "RangeQualifier{";
	if (this->graphPrev) b << "\n  \033[1mgraphPrev\033[0m = \033[36m" << this->graphPrev.id << "\033[0m";
	if (!this->name.empty()) b << "\n  \033[1mname\033[0m = \033[33m\"" << this->name << "\"\033[0m";
	if (!this->min.empty()) b << "\n  \033[1mmin\033[0m = \033[33m\"" << this->min << "\"\033[0m";
	if (!this->max.empty()) b << "\n  \033[1mmax\033[0m = \033[33m\"" << this->max << "\"\033[0m";
	string bs = b.str();
	if (!bs.empty()) str << bs << '\n';
	str << "}";
	return str.str();
}


void RangeQualifier::setGraphPrev(const NodePtr& v) {
	if (!v && graphPrev) {
		modify("graphPrev");
		graphPrev.reset();
	}
	if (!graphPrev || v->getId() != graphPrev.id) {
		modify("graphPrev");
		graphPrev.set(v);
	}
}

void RangeQualifier::setGraphPrev(const NodeId& v) {
	if (v != graphPrev.id) {
		modify("graphPrev");
		graphPrev.set(v);
	}
}

const NodePtr& RangeQualifier::getGraphPrev(bool required) {
	const NodePtr& v = graphPrev.get(repository);
	if (required && !v) {
		throw std::runtime_error("Node " + getId().str() + " is required to have graphPrev set to a non-null value.");
	}
	return v;
}


void RangeQualifier::setName(const std::string& v) {
	if (!equal(v, name)) {
		modify("name");
		name = v;
	}
}

const std::string& RangeQualifier::getName(bool required) {
	const std::string& v = name;
	if (required && v.empty()) {
		throw std::runtime_error("Node " + getId().str() + " is required to have a non-empty string name set.");
	}
	return v;
}


void RangeQualifier::setMin(const std::string& v) {
	if (!equal(v, min)) {
		modify("min");
		min = v;
	}
}

const std::string& RangeQualifier::getMin(bool required) {
	const std::string& v = min;
	if (required && v.empty()) {
		throw std::runtime_error("Node " + getId().str() + " is required to have a non-empty string min set.");
	}
	return v;
}


void RangeQualifier::setMax(const std::string& v) {
	if (!equal(v, max)) {
		modify("max");
		max = v;
	}
}

const std::string& RangeQualifier::getMax(bool required) {
	const std::string& v = max;
	if (required && v.empty()) {
		throw std::runtime_error("Node " + getId().str() + " is required to have a non-empty string max set.");
	}
	return v;
}


void RangeQualifier::encode(Encoder& e) {
	e.encode(this->graphPrev);
	e.encode(this->name);
	e.encode(this->min);
	e.encode(this->max);
}

void RangeQualifier::decode(Decoder& d) {
	d.decode(this->graphPrev);
	d.decode(this->name);
	d.decode(this->min);
	d.decode(this->max);
}


void RangeQualifier::updateHierarchyOfChildren() {
}

const NodePtr& RangeQualifier::resolvePath(const std::string& path) {
	size_t size = path.size();
	// graphPrev.*
	if (size >= 9 && path[0] == 'g' && path[1] == 'r' && path[2] == 'a' && path[3] == 'p' && path[4] == 'h' && path[5] == 'P' && path[6] == 'r' && path[7] == 'e' && path[8] == 'v') {
		// graphPrev
		if (size == 9) {
			return getGraphPrev();
		} else if (path[9] == '.') {
			return getGraphPrev()->resolvePath(path.substr(10));
		}
	}
	throw std::runtime_error("Node path '" + path + "' does not point to a node or array of nodes.");
}

