/* Automatically generated by ast-gen. DO NOT MODIFY. */
#include "maxwell/ast/nodes/SpecializedTypeExpr.hpp"
#include "maxwell/ast/Coder.hpp"
#include <cstdio>
#include <sstream>
#include <stdexcept>
using ast::SpecializedTypeExpr;
using ast::NodePtr;
using ast::NodeVector;

SpecializedTypeExpr::SpecializedTypeExpr() : Node(),
	interfaceGraph(this),
	interfaceTypeExpr(this) {}

bool SpecializedTypeExpr::isKindOf(Kind k) {
	if (Node::isKindOf(k)) return true;
	return k == kSpecializedTypeExpr;
}

bool SpecializedTypeExpr::implements(Interface i) {
	if (Node::implements(i)) return true;
	if (i == kGraphInterface) return true;
	if (i == kTypeExprInterface) return true;
	return false;
}

NodePtr SpecializedTypeExpr::copy() {
	Ptr c (new SpecializedTypeExpr);
	Node::copy(this->graphPrev, c->graphPrev);
	Node::copy(this->evaluatedType, c->evaluatedType);
	Node::copy(this->expr, c->expr);
	Node::copy(this->specExprs, c->specExprs);
	return c;
}

bool SpecializedTypeExpr::equalTo(const NodePtr& o) {
	const shared_ptr<SpecializedTypeExpr>& other = boost::dynamic_pointer_cast<SpecializedTypeExpr>(o);
	if (!other) return false;
	if (!equal(this->graphPrev, other->graphPrev)) return false;
	if (!equal(this->evaluatedType, other->evaluatedType)) return false;
	if (!equal(this->expr, other->expr)) return false;
	if (!equal(this->specExprs, other->specExprs)) return false;
	return true;
}

std::string SpecializedTypeExpr::describe(int depth) {
	std::stringstream str, b;
	if (depth == 0) return "SpecializedTypeExpr{…}";
	str << "SpecializedTypeExpr{";
	if (this->graphPrev) b << "\n  \033[1mgraphPrev\033[0m = \033[36m" << this->graphPrev.id << "\033[0m";
	if (this->evaluatedType) b << "\n  \033[1mevaluatedType\033[0m = " << indent(this->evaluatedType->describe(depth-1));
	if (this->expr) b << "\n  \033[1mexpr\033[0m = " << indent(this->expr->describe(depth-1));
	if (!this->specExprs.empty()) b << "\n  \033[1mspecExprs\033[0m = " << indent(describeVector(this->specExprs, depth-1));
	string bs = b.str();
	if (!bs.empty()) str << bs << '\n';
	str << "}";
	return str.str();
}


void SpecializedTypeExpr::setGraphPrev(const NodePtr& v) {
	if (!v && graphPrev) {
		modify("graphPrev");
		graphPrev.reset();
	}
	if (!graphPrev || v->getId() != graphPrev.id) {
		modify("graphPrev");
		graphPrev.set(v);
	}
}

void SpecializedTypeExpr::setGraphPrev(const NodeId& v) {
	if (v != graphPrev.id) {
		modify("graphPrev");
		graphPrev.set(v);
	}
}

const NodePtr& SpecializedTypeExpr::getGraphPrev(bool required) {
	const NodePtr& v = graphPrev.get(repository);
	if (required && !v) {
		throw std::runtime_error("Node " + getId().str() + " is required to have graphPrev set to a non-null value.");
	}
	return v;
}


void SpecializedTypeExpr::setEvaluatedType(const NodePtr& v) {
	if (v && !v->isKindOf(kGenericType) && !v->isKindOf(kInvalidType) && !v->isKindOf(kNilType) && !v->isKindOf(kDefinedType) && !v->isKindOf(kUnionType) && !v->isKindOf(kTupleType) && !v->isKindOf(kFuncType) && !v->isKindOf(kTypeSet) && !v->isKindOf(kQualifiedType) && !v->isKindOf(kSpecializedType) && !v->isKindOf(kUnionMappedType) && !v->isKindOf(kOneTupleMappedType) && !v->isKindOf(kCastType) && !v->isKindOf(kNativeType) && !v->isKindOf(kMutableType) && !v->isKindOf(kMutableCastType) && !v->isKindOf(kImmutableCastType)) {
		throw std::runtime_error("'evaluatedType' of " + id.str() + " needs to be of kind {GenericType, InvalidType, NilType, DefinedType, UnionType, TupleType, FuncType, TypeSet, QualifiedType, SpecializedType, UnionMappedType, OneTupleMappedType, CastType, NativeType, MutableType, MutableCastType, ImmutableCastType} or implement interface {}, got " + v->getClassName() + " (" + v->getId().str() + ") instead.");
	}
	if (!equal(v, evaluatedType)) {
		modify("evaluatedType");
		evaluatedType = v;
	}
}

const NodePtr& SpecializedTypeExpr::getEvaluatedType(bool required) {
	const NodePtr& v = evaluatedType;
	if (required && !v) {
		throw std::runtime_error("Node " + getId().str() + " is required to have evaluatedType set to a non-null value.");
	}
	return v;
}


void SpecializedTypeExpr::setExpr(const NodePtr& v) {
	if (v && !v->isKindOf(kNamedTypeExpr) && !v->isKindOf(kNilTypeExpr) && !v->isKindOf(kUnionTypeExpr) && !v->isKindOf(kTupleTypeExpr) && !v->isKindOf(kQualifiedTypeExpr) && !v->isKindOf(kSpecializedTypeExpr) && !v->isKindOf(kFuncTypeExpr) && !v->isKindOf(kNativeTypeExpr) && !v->isKindOf(kMutableTypeExpr)) {
		throw std::runtime_error("'expr' of " + id.str() + " needs to be of kind {NamedTypeExpr, NilTypeExpr, UnionTypeExpr, TupleTypeExpr, QualifiedTypeExpr, SpecializedTypeExpr, FuncTypeExpr, NativeTypeExpr, MutableTypeExpr} or implement interface {}, got " + v->getClassName() + " (" + v->getId().str() + ") instead.");
	}
	if (!equal(v, expr)) {
		modify("expr");
		expr = v;
	}
}

const NodePtr& SpecializedTypeExpr::getExpr(bool required) {
	const NodePtr& v = expr;
	if (required && !v) {
		throw std::runtime_error("Node " + getId().str() + " is required to have expr set to a non-null value.");
	}
	return v;
}


void SpecializedTypeExpr::setSpecExprs(const NodeVector& v) {
	if (!equal(v, specExprs)) {
		modify("specExprs");
		specExprs = v;
	}
}

const NodeVector& SpecializedTypeExpr::getSpecExprs(bool required) {
	const NodeVector& v = specExprs;
	return v;
}


void SpecializedTypeExpr::encode(Encoder& e) {
	e.encode(this->graphPrev);
	e.encode(this->evaluatedType);
	e.encode(this->expr);
	e.encode(this->specExprs);
}

void SpecializedTypeExpr::decode(Decoder& d) {
	d.decode(this->graphPrev);
	d.decode(this->evaluatedType);
	d.decode(this->expr);
	d.decode(this->specExprs);
}


void SpecializedTypeExpr::updateHierarchyOfChildren() {
	if (this->evaluatedType) this->evaluatedType->updateHierarchy(id + "evaluatedType", repository, this);
	if (this->expr) this->expr->updateHierarchy(id + "expr", repository, this);
	for (unsigned i = 0; i < this->specExprs.size(); i++) {
		char buf[32]; snprintf(buf, 31, "%i", i);
		this->specExprs[i]->updateHierarchy((id + "specExprs") + buf, repository, this);
	}
}

const NodePtr& SpecializedTypeExpr::resolvePath(const std::string& path) {
	size_t size = path.size();
	// .*
	if (true) {
		// e.*
		if (size >= 1 && path[0] == 'e') {
			// evaluatedType.*
			if (size >= 13 && path[1] == 'v' && path[2] == 'a' && path[3] == 'l' && path[4] == 'u' && path[5] == 'a' && path[6] == 't' && path[7] == 'e' && path[8] == 'd' && path[9] == 'T' && path[10] == 'y' && path[11] == 'p' && path[12] == 'e') {
				// evaluatedType
				if (size == 13) {
					return getEvaluatedType();
				} else if (path[13] == '.') {
					return getEvaluatedType()->resolvePath(path.substr(14));
				}
			}
			// expr.*
			if (size >= 4 && path[1] == 'x' && path[2] == 'p' && path[3] == 'r') {
				// expr
				if (size == 4) {
					return getExpr();
				} else if (path[4] == '.') {
					return getExpr()->resolvePath(path.substr(5));
				}
			}
		}
		// graphPrev.*
		if (size >= 9 && path[0] == 'g' && path[1] == 'r' && path[2] == 'a' && path[3] == 'p' && path[4] == 'h' && path[5] == 'P' && path[6] == 'r' && path[7] == 'e' && path[8] == 'v') {
			// graphPrev
			if (size == 9) {
				return getGraphPrev();
			} else if (path[9] == '.') {
				return getGraphPrev()->resolvePath(path.substr(10));
			}
		}
		// specExprs.*
		if (size >= 9 && path[0] == 's' && path[1] == 'p' && path[2] == 'e' && path[3] == 'c' && path[4] == 'E' && path[5] == 'x' && path[6] == 'p' && path[7] == 'r' && path[8] == 's') {
			// specExprs
			if (size == 9) {
				throw std::runtime_error("Path '" + path + "' refers to an array instead of a concrete array element.");
			} else if (path[9] == '.') {
				size_t dot = path.find(".", 10);
				string idx_str = path.substr(10, dot);
				int idx = atoi(idx_str.c_str());
				const NodeVector& a = getSpecExprs();
				if (idx < 0 || idx >= (int)a.size()) {
					throw std::runtime_error("Index into array '" + path.substr(0, 9) + "' is out of bounds.");
				}
				if (dot == string::npos) {
					return a[idx];
				} else {
					return a[idx]->resolvePath(path.substr(dot + 1));
				}
			}
		}
	}
	throw std::runtime_error("Node path '" + path + "' does not point to a node or array of nodes.");
}

NodeVector SpecializedTypeExpr::getChildren() {
	NodeVector v;
	if (const NodePtr& n = this->getEvaluatedType(false)) v.push_back(n);
	if (const NodePtr& n = this->getExpr(false)) v.push_back(n);
	v.insert(v.end(), this->specExprs.begin(), this->specExprs.end());
	return v;
}

