/* Automatically generated by ast-gen. DO NOT MODIFY. */
#include "maxwell/ast/nodes/TupleTypeArg.hpp"
#include "maxwell/ast/Coder.hpp"
#include <cstdio>
#include <sstream>
#include <stdexcept>
using ast::TupleTypeArg;
using ast::NodePtr;
using ast::NodeVector;

TupleTypeArg::TupleTypeArg() : Node(),
	interfaceCallable(this),
	interfaceNamed(this) {}

bool TupleTypeArg::isKindOf(Kind k) {
	if (Node::isKindOf(k)) return true;
	return k == kTupleTypeArg;
}

bool TupleTypeArg::implements(Interface i) {
	if (Node::implements(i)) return true;
	if (i == kCallableInterface) return true;
	if (i == kNamedInterface) return true;
	return false;
}

NodePtr TupleTypeArg::copy() {
	Ptr c (new TupleTypeArg);
	Node::copy(this->name, c->name);
	Node::copy(this->type, c->type);
	return c;
}

bool TupleTypeArg::equalTo(const NodePtr& o) {
	const shared_ptr<TupleTypeArg>& other = boost::dynamic_pointer_cast<TupleTypeArg>(o);
	if (!other) return false;
	if (!equal(this->name, other->name)) return false;
	if (!equal(this->type, other->type)) return false;
	return true;
}

std::string TupleTypeArg::describe(int depth) {
	std::stringstream str, b;
	if (!name.empty()) str << name << ": "; str << type->describe(depth-1);
	return str.str();
}


void TupleTypeArg::setName(const std::string& v) {
	if (!equal(v, name)) {
		modify("name");
		name = v;
	}
}

const std::string& TupleTypeArg::getName(bool required) {
	const std::string& v = name;
	if (required && v.empty()) {
		throw std::runtime_error("Node " + getId().str() + " is required to have a non-empty string name set.");
	}
	return v;
}


void TupleTypeArg::setType(const NodePtr& v) {
	if (v && !v->isKindOf(kGenericType) && !v->isKindOf(kInvalidType) && !v->isKindOf(kNilType) && !v->isKindOf(kDefinedType) && !v->isKindOf(kUnionType) && !v->isKindOf(kTupleType) && !v->isKindOf(kFuncType) && !v->isKindOf(kTypeSet) && !v->isKindOf(kQualifiedType) && !v->isKindOf(kSpecializedType) && !v->isKindOf(kUnionMappedType) && !v->isKindOf(kOneTupleMappedType) && !v->isKindOf(kCastType)) {
		throw std::runtime_error("'type' of " + id.str() + " needs to be of kind {GenericType, InvalidType, NilType, DefinedType, UnionType, TupleType, FuncType, TypeSet, QualifiedType, SpecializedType, UnionMappedType, OneTupleMappedType, CastType} or implement interface {}, got " + v->getClassName() + " (" + v->getId().str() + ") instead.");
	}
	if (!equal(v, type)) {
		modify("type");
		type = v;
	}
}

const NodePtr& TupleTypeArg::getType(bool required) {
	const NodePtr& v = type;
	if (required && !v) {
		throw std::runtime_error("Node " + getId().str() + " is required to have type set to a non-null value.");
	}
	return v;
}


void TupleTypeArg::encode(Encoder& e) {
	e.encode(this->name);
	e.encode(this->type);
}

void TupleTypeArg::decode(Decoder& d) {
	d.decode(this->name);
	d.decode(this->type);
}


void TupleTypeArg::updateHierarchyOfChildren() {
	if (this->type) this->type->updateHierarchy(id + "type", repository, this);
}

const NodePtr& TupleTypeArg::resolvePath(const std::string& path) {
	size_t size = path.size();
	// type.*
	if (size >= 4 && path[0] == 't' && path[1] == 'y' && path[2] == 'p' && path[3] == 'e') {
		// type
		if (size == 4) {
			return getType();
		} else if (path[4] == '.') {
			return getType()->resolvePath(path.substr(5));
		}
	}
	throw std::runtime_error("Node path '" + path + "' does not point to a node or array of nodes.");
}

NodeVector TupleTypeArg::getChildren() {
	NodeVector v;
	if (const NodePtr& n = this->getType(false)) v.push_back(n);
	return v;
}

