/* Automatically generated by ast-gen. DO NOT MODIFY. */
#include "maxwell/ast/nodes/UnionMappedType.hpp"
#include "maxwell/ast/Coder.hpp"
#include <cstdio>
#include <sstream>
#include <stdexcept>
using ast::UnionMappedType;
using ast::NodePtr;
using ast::NodeVector;

UnionMappedType::UnionMappedType() : Node() {}

bool UnionMappedType::isKindOf(Kind k) {
	if (Node::isKindOf(k)) return true;
	return k == kUnionMappedType;
}

bool UnionMappedType::implements(Interface i) {
	if (Node::implements(i)) return true;
	return false;
}

NodePtr UnionMappedType::copy() {
	Ptr c (new UnionMappedType);
	Node::copy(this->in, c->in);
	Node::copy(this->out, c->out);
	return c;
}

bool UnionMappedType::equalTo(const NodePtr& o) {
	const shared_ptr<UnionMappedType>& other = boost::dynamic_pointer_cast<UnionMappedType>(o);
	if (!other) return false;
	if (!equal(this->in, other->in)) return false;
	if (!equal(this->out, other->out)) return false;
	return true;
}

std::string UnionMappedType::describe(int depth) {
	std::stringstream str, b;
	str << out->describe(depth) << '(' << in->describe(depth) << ')';
	return str.str();
}


void UnionMappedType::setIn(const NodePtr& v) {
	if (v && !v->isKindOf(kGenericType) && !v->isKindOf(kInvalidType) && !v->isKindOf(kNilType) && !v->isKindOf(kDefinedType) && !v->isKindOf(kUnionType) && !v->isKindOf(kTupleType) && !v->isKindOf(kFuncType) && !v->isKindOf(kTypeSet) && !v->isKindOf(kQualifiedType) && !v->isKindOf(kSpecializedType) && !v->isKindOf(kUnionMappedType) && !v->isKindOf(kOneTupleMappedType) && !v->isKindOf(kCastType) && !v->isKindOf(kNativeType) && !v->isKindOf(kMutableType) && !v->isKindOf(kMutableCastType) && !v->isKindOf(kImmutableCastType)) {
		throw std::runtime_error("'in' of " + id.str() + " needs to be of kind {GenericType, InvalidType, NilType, DefinedType, UnionType, TupleType, FuncType, TypeSet, QualifiedType, SpecializedType, UnionMappedType, OneTupleMappedType, CastType, NativeType, MutableType, MutableCastType, ImmutableCastType} or implement interface {}, got " + v->getClassName() + " (" + v->getId().str() + ") instead.");
	}
	if (!equal(v, in)) {
		modify("in");
		in = v;
	}
}

const NodePtr& UnionMappedType::getIn(bool required) {
	const NodePtr& v = in;
	if (required && !v) {
		throw std::runtime_error("Node " + getId().str() + " is required to have in set to a non-null value.");
	}
	return v;
}


void UnionMappedType::setOut(const NodePtr& v) {
	if (v && !v->isKindOf(kGenericType) && !v->isKindOf(kInvalidType) && !v->isKindOf(kNilType) && !v->isKindOf(kDefinedType) && !v->isKindOf(kUnionType) && !v->isKindOf(kTupleType) && !v->isKindOf(kFuncType) && !v->isKindOf(kTypeSet) && !v->isKindOf(kQualifiedType) && !v->isKindOf(kSpecializedType) && !v->isKindOf(kUnionMappedType) && !v->isKindOf(kOneTupleMappedType) && !v->isKindOf(kCastType) && !v->isKindOf(kNativeType) && !v->isKindOf(kMutableType) && !v->isKindOf(kMutableCastType) && !v->isKindOf(kImmutableCastType)) {
		throw std::runtime_error("'out' of " + id.str() + " needs to be of kind {GenericType, InvalidType, NilType, DefinedType, UnionType, TupleType, FuncType, TypeSet, QualifiedType, SpecializedType, UnionMappedType, OneTupleMappedType, CastType, NativeType, MutableType, MutableCastType, ImmutableCastType} or implement interface {}, got " + v->getClassName() + " (" + v->getId().str() + ") instead.");
	}
	if (!equal(v, out)) {
		modify("out");
		out = v;
	}
}

const NodePtr& UnionMappedType::getOut(bool required) {
	const NodePtr& v = out;
	if (required && !v) {
		throw std::runtime_error("Node " + getId().str() + " is required to have out set to a non-null value.");
	}
	return v;
}


void UnionMappedType::encode(Encoder& e) {
	e.encode(this->in);
	e.encode(this->out);
}

void UnionMappedType::decode(Decoder& d) {
	d.decode(this->in);
	d.decode(this->out);
}


void UnionMappedType::updateHierarchyOfChildren() {
	if (this->in) this->in->updateHierarchy(id + "in", repository, this);
	if (this->out) this->out->updateHierarchy(id + "out", repository, this);
}

const NodePtr& UnionMappedType::resolvePath(const std::string& path) {
	size_t size = path.size();
	// .*
	if (true) {
		// in.*
		if (size >= 2 && path[0] == 'i' && path[1] == 'n') {
			// in
			if (size == 2) {
				return getIn();
			} else if (path[2] == '.') {
				return getIn()->resolvePath(path.substr(3));
			}
		}
		// out.*
		if (size >= 3 && path[0] == 'o' && path[1] == 'u' && path[2] == 't') {
			// out
			if (size == 3) {
				return getOut();
			} else if (path[3] == '.') {
				return getOut()->resolvePath(path.substr(4));
			}
		}
	}
	throw std::runtime_error("Node path '" + path + "' does not point to a node or array of nodes.");
}

NodeVector UnionMappedType::getChildren() {
	NodeVector v;
	if (const NodePtr& n = this->getIn(false)) v.push_back(n);
	if (const NodePtr& n = this->getOut(false)) v.push_back(n);
	return v;
}

